### ISSUE TITLE
Using more than one  sensor instances

### ISSUE THREAD

**Issue by juergs** [amigatommy/BME680-UniversalSensor#1]
Hello Thomas,
i pretend to use more than one sensor in fhem.
How is the sensor-id configurable (eeprom during serial setup) and is LaCrosse-Gateway capable of receiving these instances?

regards,
juergen

**Comment by juergs** [comment]
Sorry, could answer by myself ;-)

> (COM6) BME680 wireless sensor V3.0
(COM6) Compiled: Fri Dec 07 17:57:22 2018
(COM6) Protocol: UniversalSensor
(COM6) BSEC version: 1.4.5.1<LF>ESP Core Version: 2_4_0_RC1
(COM6) ESP SDK Version: 2.0.0(656edbf)
(COM6) 
(COM6) Do you want to delete settings in EEPROM (Y/N)?
(COM6) Y
(COM6) Settings deleted.
(COM6) 
(COM6) Node-ID is: 255 (0xFF)
(COM6) New value (1-254): 
(COM6) Error, try again !
(COM6) received: 0
(COM6) Y112
(COM6) Node-ID set to: 112 (0x70)

By configuration via serial connection after reset with 115200 Baud Bitrate 8N1.

(COM6) Save settings ...
(COM6) Node-ID           : 112 (0x70)
(COM6) Altitude          : 0.0m
(COM6) Temperature offset: 0.0 degrees celsius
(COM6) 
(COM6) RFM69  init ... done
(COM6) BME680 init ... done
(COM6) BH1750 init ... done
(COM6) Ready, start measuring ...
(COM6) 
(COM6) [63321.00] P: 994.3| T: 38.24| rH: 18.11| IAQ: 25.00 (0)| Gas: 1184.00| Light: 15.42lx
(COM6) [66321.00] P: 994.2| T: 38.28| rH: 18.00| IAQ: 25.00 (0)| Gas: 1443.00| Light: 15.42lx
(COM6) [69321.00] P: 994.3| T: 38.32| rH: 17.88| IAQ: 25.00 (0)| Gas: 2019.00| Light: 15.42lx
(COM6) [72321.00] P: 994.3| T: 38.33| rH: 17.83| IAQ: 25.00 (0)| Gas: 2560.00| Light: 15.42lx
(COM6) [75321.00] P: 994.3| T: 38.35| rH: 17.77| IAQ: 25.00 (0)| Gas: 3147.00| Light: 15.42lx
(COM6) [78321.00] P: 994.3| T: 38.33| rH: 17.77| IAQ: 25.00 (0)| Gas: 3593.00| Light: 15.42lx
(COM6) [81321.00] P: 994.3| T: 38.30| rH: 17.79| IAQ: 25.00 (0)| Gas: 4028.00| Light: 15.42lx
(COM6) [84321.00] P: 994.2| T: 38.26| rH: 17.82| IAQ: 25.00 (0)| Gas: 4430.00| Light: 15.42lx
(COM6) [87321.00] P: 994.2| T: 38.24| rH: 17.83| IAQ: 25.00 (0)| Gas: 4843.00| Light: 15.42lx
(COM6) [90321.00] P: 994.3| T: 38.26| rH: 17.80| IAQ: 25.00 (0)| Gas: 5237.00| Light: 15.42lx
(COM6) [93321.00] P: 994.3| T: 38.25| rH: 17.83| IAQ: 25.00 (0)| Gas: 5602.00| Light: 15.42lx
(COM6) [96321.00] P: 994.2| T: 38.25| rH: 17.82| IAQ: 25.00 (0)| Gas: 5926.00| Light: 74.58lx
(COM6) [99321.00] P: 994.2| T: 38.27| rH: 17.81| IAQ: 25.00 (0)| Gas: 6275.00| Light: 111.67lx
(COM6) [102321.00] P: 994.3| T: 38.28| rH: 19.40| IAQ: 25.00 (0)| Gas: 6411.00| Light: 21.85lx
(COM6) [105321.00] P: 994.3| T: 38.33| rH: 21.43| IAQ: 25.00 (0)| Gas: 6836.00| Light: 546.25lx
(COM6) [108321.00] P: 994.3| T: 38.42| rH: 21.17| IAQ: 25.00 (0)| Gas: 7223.00| Light: 882.92lx

**Comment by amigatommy** [comment]
Sorry, you were faster ;o)
Yes, you can make all settings via serial connection after reset.

regards,
Thomas
